apiVersion: apps/v1
kind: Deployment
metadata:
  name: nba-statistics-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nba-statistics
  template:
    metadata:
      labels:
        app: nba-statistics
    spec:
      containers:
      - name: nba-statistics
        image: nba-statistics:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        env:
          - name: POSTGRES_HOST
            value: my-postgres.default.svc.cluster.local
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres123
          - name: POSTGRES_DB
            value: mydb
          - name: REDIS_HOST
            value: my-redis-master.default.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: nba-statistics-service
spec:
  selector:
    app: nba-statistics
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres123
          - name: POSTGRES_DB
            value: mydb
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:6
        ports:
          - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
