apiVersion: apps/v1
kind: Deployment
metadata:
  name: nba-statistics-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nba-statistics
  template:
    metadata:
      labels:
        app: nba-statistics
    spec:
      containers:
      - name: nba-statistics
        image: nba-statistics:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        env:
          - name: POSTGRES_HOST
            value: postgres-service.default.svc.cluster.local
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres123
          - name: POSTGRES_DB
            value: mydb
          - name: REDIS_HOST
            value: redis-service.default.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: nba-statistics-service
  namespace: default
spec:
  selector:
    app: nba-statistics
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres123
          - name: POSTGRES_DB
            value: mydb
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: default
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:6
        ports:
          - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: default
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nba-statistics-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: laughing-memory-x5wxvr5rgpv529wv-8080.app.github.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nba-statistics-service
            port:
              number: 8080
